# stages:
#   - testing
#   - build
#   - upload
#   - deploy-to-dev
#   - deploy

# testing:FRONTEND-TEST:
#   stage: testing
#   script:
#     - cd src/app
#     - npm install --silent
#     # - jest --collectCoverage=true
#     - npm test -- --collectCoverage
#   artifacts:
#     paths:
#       - ./src/app/coverage
#     expire_in: 1 week
#   only:
#     - master
#   tags:
#     - merlin

# testing:INTEGRATION-TEST:
#   stage: testing
#   script:
#     - pwd
#   only:
#     - master
#   tags:
#     - merlin

# BUILD-DEV:
#   stage: build
#   script:
#     - cd src/app
#     - docker image rm phr-react || true
#     - docker build
#       --build-arg REACT_APP_SERVER_LOCATION=$REACT_APP_SERVER_LOCATION
#       --build-arg REACT_APP_FLAGR_URL=$REACT_APP_FLAGR_URL
#       --build-arg REACT_APP_API_BIMAPHR_URL=$REACT_APP_API_BIMAPHR_URL
#       --build-arg REACT_APP_GOOGLE_APIKEY=$REACT_APP_GOOGLE_APIKEY
#       -t phr-react .
#     - docker tag phr-react $IMAGE:dev
#   only:
#     - master
#   tags:
#     - merlin
#   environment:
#     name: dev

# BUILD-PROD:
#   stage: build
#   script:
#     - cd src/app
#     - docker image rm phr-react || true
#     - docker build
#       --build-arg REACT_APP_SERVER_LOCATION=$REACT_APP_SERVER_LOCATION
#       --build-arg REACT_APP_FLAGR_URL=$REACT_APP_FLAGR_URL
#       --build-arg REACT_APP_API_BIMAPHR_URL=$REACT_APP_API_BIMAPHR_URL
#       --build-arg REACT_APP_GOOGLE_APIKEY=$REACT_APP_GOOGLE_APIKEY
#       -t phr-react-prod .
#   only:
#     - tags
#   tags:
#     - merlin
#   environment:
#     name: prod

# # UPLOAD:
# #   stage: upload
# #   script:
# #     - docker login $HARBOR_H -u $HARBOR_U -p $HARBOR_T
# #     - docker push $IMAGE:dev
# #   only:
# #     - master
# #   tags:
# #     - merlin
# #   environment:
# #     name: prod

# DEPLOY-TO-DEV:
#   stage: deploy-to-dev
#   script:
#     - docker stop phr-FE || true
#     - docker rm phr-FE || true
#     - docker run --name phr-FE -p $DEV_PORT:80 -d phr-react:latest
#   only:
#     - master
#   tags:
#     - merlin

# DEPLOY-TO-PROD:
#   stage: deploy
#   script:
#     - docker tag phr-react-prod $IMAGE:$CI_COMMIT_TAG
#     - docker login $HARBOR_H -u $HARBOR_U -p $HARBOR_T
#     - docker push $IMAGE:$CI_COMMIT_TAG
#     - gcloud auth activate-service-account --key-file $GCLOUD
#     - gcloud beta container clusters get-credentials $REGCRED --region $REGION --project $PROJECT_NAME
#     - kubectl set image deployments bimaphr -n targaryen-staging bimaphr=$IMAGE:$CI_COMMIT_TAG --record
#   only:
#     - tags
#   tags:
#     - merlin
#   environment:
#     name: prod
